CONFIG_NAME: 'sigm_kidney'
GPU_ID: '0'
CUDA: False
VERBOSE: False

# Dataset options
DATA:
  DATASET: 'kidney'
  CATEGORICAL_KEYS: ['AMIS','BMIS','CARDARREST_NEURO','COD_CAD_DON','DIAB','DRMIS','EBV_SEROSTATUS', 'EBV_IGG_CAD_DON',
                      'ETHCAT','ETHCAT_DON', # drop race
                      'GENDER','GENDER_DON','HIST_CANCER_DON',
                      'HIST_CIG_DON','HIST_COCAINE_DON','HIST_HYPERTENS_DON','INOTROP_SUPPORT_DON',
                      'MALIG','NON_HRT_DON','PERIP_VASC','PRE_TX_TXFUS','PROTEIN_URINE','CMV_RECIPIENT',
                      'CKD_CAUSE','DONOR_DIABETES','DONOR_HBV','RECIPIENT_HBV','DONOR_HCV','HCV_NAT',
                      'DONOR_HIV','RECIPIENT_HIV','TX_DATE_BUCKET']
  CONTINUOUS_KEYS: ['AGE','AGE_DON','BUN_DON','CREAT_DON','HGT_CM_CALC','HGT_CM_DON_CALC',
                      'WGT_KG_CALC','WGT_KG_DON_CALC','PRA_REC','TIME_ON_DIALYSIS']
  TARGET: "Tgt4"
  EVENT: "Tgt4_Event"
  NORMALIZE: True

# Training options
TRAIN:
  BATCH_SIZE: 512
  MAX_EPOCH: 1000
  PATIENCE: 20
  LR: [1e-5, 1e-4, 1e-3] # [1e-4, 1e-3, 1e-2, 1e-1]
  L2_COEFF: [1e-5, 1e-4] # [1e-6, 1e-5, 1e-4, 1e-3, 1e-2]
  DROP_INPUT: 0.2
  DROP_HIDDEN: '[0.5, 0.5, 0.5]'
  LAYER_SIZES: '[100, 100, 100]'
  BATCH_NORM: True
  MODEL: "rank"
  LOSS_TYPE: 'rank_loss'
  F_RANK: 'sigm'
