CONFIG_NAME: 'rankboost_colon_death'
GPU_ID: '0'
CUDA: False
VERBOSE: False

# Dataset options
DATA:
  DATASET: 'colon_death'
  CATEGORICAL_KEYS: ["rx", "sex", "obstruct", "perfor", "adhere", 
                    "nodes", "differ", "extent", "surg", "node4"]
  CONTINUOUS_KEYS: ["age"]
  TARGET: "time"
  EVENT: "status"
  NORMALIZE: True

# Training options
TRAIN:
  BATCH_SIZE: 128
  MAX_EPOCH: 1000
  PATIENCE: 20
  LR: [1e-2] # [1e-3, 1e-2]
  L2_COEFF: [5e-3] # [5e-4, 1e-2]
  DROP_INPUT: 0.2
  DROP_HIDDEN: '[0.5, 0.5, 0.5]'
  LAYER_SIZES: '[100, 100, 100]'
  BATCH_NORM: True
  MODEL: "rank"
  LOSS_TYPE: 'rank_loss'
  F_RANK: 'RankBoost'
