CONFIG_NAME: 'emd_cens06_support2'
GPU_ID: '0'
CUDA: False
VERBOSE: False

# Dataset options
DATA:
  PATH: '/local_workspace/piepmike/Survival_Pytorch_EMD/datasets/'
  SPLITS: '[0, 1, 2, 3, 4]'
  DATASET: 'support2'
  CATEGORICAL_KEYS: ["sex", "income", "race", "ca", "dnr", "sfdm2", "dzgroup", "dzclass"]
  CONTINUOUS_KEYS: ["age", "num.co", "edu", "scoma", "avtisst", "sps", "aps", "surv2m", "surv6m",
                                "hday", "diabetes", "dementia", "prg2m", "prg6m", "dnrday", "meanbp", "wblc",
                                "hrt", "resp", "temp", "pafi", "alb", "bili", "crea", "sod", "ph", "glucose",
                                "bun", "urine", "adlp", "adls", "adlsc"]
  TARGET: "d.time"
  EVENT: "death"
  
  ADD_CENS: True
  PROBA: 0.6

# Training options
TRAIN:
  BATCH_SIZE: 512
  MAX_EPOCH: 1000
  PATIENCE: 20
  LR: [1e-2] # [1e-3, 1e-2]
  L2_COEFF: [5e-3] # [5e-4, 1e-2]
  DROP_INPUT: 0.2
  DROP_HIDDEN: '[0.5, 0.5, 0.5]'
  LAYER_SIZES: '[100, 100, 100]'
  BATCH_NORM: True
  MODEL: "emd"
  LOSS_TYPE: "emd_loss"
  DIV_TIME: 1

EMD:
  PRIOR: [1.]
