CONFIG_NAME: 'log_sigm_aids3'
GPU_ID: '0'
CUDA: False
VERBOSE: False

# Dataset options
DATA:
  DATASET: 'aids3'
  CATEGORICAL_KEYS: ["state", "sex", "T.categ", "zid"]
  CONTINUOUS_KEYS: ["age"]
  TARGET: "time"
  EVENT: "status"
  NORMALIZE: True

# Training options
TRAIN:
  BATCH_SIZE: 512
  MAX_EPOCH: 1000
  PATIENCE: 20
  LR: [1e-2] # [1e-3, 1e-2]
  L2_COEFF: [5e-3] # [5e-4, 1e-2]
  DROP_INPUT: 0.2
  DROP_HIDDEN: '[0.5, 0.5, 0.5]'
  LAYER_SIZES: '[100, 100, 100]'
  BATCH_NORM: True
  MODEL: "likelihood"
  LOSS_TYPE: 'rank_loss'
  F_RANK: 'log_sigm'
